package com.tpo3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import org.junit.AfterClass;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.JavascriptExecutor;

import static org.junit.Assert.fail;

import java.io.File;
import java.util.*;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class AuthTest {
  private static WebDriver driver;
  private static Map<String, Object> vars;
  static JavascriptExecutor js;


  @BeforeClass
  public static void setUp() {
    // Здесь логинимся в фаерфокс профиль в котором я залогинин в яндексе но не залогинин в авиасейлс
    FirefoxProfile profile = new FirefoxProfile(new File("/Users/ubica/Library/Application Support/Firefox/Profiles/flsbiqey.tpo3Auth"));
    FirefoxOptions options = new FirefoxOptions();
    options.setProfile(profile);
    driver = new FirefoxDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterClass
  public static void tearDown() {
    driver.quit();
  }

  @Test
  public void test1_auth() {
    AuthPage.login(driver, vars);
  }

  @Test
  public void test2_signout() {
    driver.get(Shared.MainPageURL);
    AuthPage.signout(driver, vars);
  }

  @Test
  public void test3_invalid_auth() {
    driver.quit();
    driver = new FirefoxDriver();

    driver.manage().deleteAllCookies();
    Shared.pause(2000);
    driver.navigate().refresh();
    Shared.pause(3000);

    try {
        AuthPage.login(driver, vars);
        fail("Expected ElementClickInterceptedException but it was not thrown");
    } catch (ElementClickInterceptedException e) {}
  }
}
