package com.tpo3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import java.util.*;

public class HotelSearch {
  private WebDriver driver;
  private Map<String, Object> vars;

  @Before
  public void setUp() {
    FirefoxOptions options = new FirefoxOptions();
    options.addArguments("-profile");
    options.addArguments("/Users/ubica/Library/Application Support/Firefox/Profiles/8pnib0dd.default-esr-1");
    
    driver = new FirefoxDriver(options);
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
 
  @Test
  public void hotelSearch() {
    HotelPage.search(driver, vars);
  }

  @Test
  public void hotelSearchWithFilter() {
    HotelPage.search(driver, vars);
    HotelPage.filter(driver, vars);
  }
}
