package com.tpo3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import java.util.*;

public class ImpressionSearch {
  private WebDriver driver;
  private Map<String, Object> vars;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void impressionSearch() {
    ImpressionPage.search(driver, vars);
  }
}
