package com.tpo3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
public class TicketSearch {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    FirefoxOptions options = new FirefoxOptions();
    options.addArguments("-profile");
    options.addArguments("/Users/ubica/Library/Application Support/Firefox/Profiles/8pnib0dd.default-esr-1");
    
    driver = new FirefoxDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void ticketSearch() { 
    TicketPage.search(driver, vars);
  }

  @Test
  public void ticketSearchWithFilter() { 
    TicketPage.search(driver, vars);
    TicketPage.filter(driver, vars);
  }
}
